// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var Belt_Array = require("rescript/lib/js/belt_Array.js");

function tap(arr, fn) {
  return Belt_Array.map(arr, (function (it) {
                Curry._1(fn, it);
                return it;
              }));
}

var $$Array = {
  tap: tap
};

function toArray(input) {
  return input.trim().split("\n");
}

var Input = {
  toArray: toArray
};

function toArray$1(str) {
  return Array.from(str);
}

var $$String = {
  toArray: toArray$1
};

exports.$$Array = $$Array;
exports.Input = Input;
exports.$$String = $$String;
/* No side effect */
