// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var Belt_Array = require("rescript/lib/js/belt_Array.js");
var Belt_SetString = require("rescript/lib/js/belt_SetString.js");

function sum(counts) {
  return Belt_Array.reduce(counts, 0, (function (acc, value) {
                return acc + value | 0;
              }));
}

function splitToGroup(input) {
  return input.split("\n\n");
}

function splitToPerson(input) {
  return input.split("\n");
}

function splitToAnswers(input) {
  return input.split("");
}

function toAllAnswers(input) {
  return input.replace(/\n/g, "").split("");
}

function toAllIntersected(sets) {
  var allQuestions = Belt_SetString.fromArray("abcdefghijklmnopqrstuvwxyz".split(""));
  return Belt_Array.reduce(sets, allQuestions, Belt_SetString.intersect);
}

function toAllYesSet(input) {
  return toAllIntersected(Belt_Array.map(Belt_Array.map(input.split("\n"), splitToAnswers), Belt_SetString.fromArray));
}

function part1(input) {
  return sum(Belt_Array.map(Belt_Array.map(Belt_Array.map(input.split("\n\n"), toAllAnswers), Belt_SetString.fromArray), Belt_SetString.size));
}

function part2(input) {
  return sum(Belt_Array.map(Belt_Array.map(input.split("\n\n"), toAllYesSet), Belt_SetString.size));
}

function main(param) {
  var input = Fs.readFileSync("input/Week1/Year2020Day6.input.txt", "utf8");
  console.log("part1: ");
  console.log(part1(input));
  console.log("part2: ");
  console.log(part2(input));
}

main(undefined);

exports.sum = sum;
exports.splitToGroup = splitToGroup;
exports.splitToPerson = splitToPerson;
exports.splitToAnswers = splitToAnswers;
exports.toAllAnswers = toAllAnswers;
exports.toAllIntersected = toAllIntersected;
exports.toAllYesSet = toAllYesSet;
exports.part1 = part1;
exports.part2 = part2;
exports.main = main;
/*  Not a pure module */
